In [14]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.0


In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.94793516,  0.5231623 , -0.58516455, -0.27086276,  0.49766904,
         0.50770223,  0.07812713,  0.50418687, -0.12841138, -1.440588  ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.03671921, 0.15987583, 0.05277674, 0.07226734, 0.15585157,
        0.15742314, 0.10244869, 0.15687071, 0.08333126, 0.02243556]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

1.8488178

In [21]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [22]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
   1/1875 [..............................] - ETA: 13:55 - loss: 2.3064 - accuracy: 0.1875

2023-01-26 23:28:04.190251: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 12s 6ms/step - loss: 0.2871 - accuracy: 0.9171
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1378 - accuracy: 0.9592
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1023 - accuracy: 0.9695
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0815 - accuracy: 0.9756
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0687 - accuracy: 0.9789


In [23]:
model.evaluate(x_test,  y_test, verbose=2)

2023-01-26 23:29:20.075752: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


313/313 - 2s - loss: 0.0725 - accuracy: 0.9780 - 2s/epoch - 5ms/step


[0.07253830879926682, 0.9780000448226929]

In [24]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [25]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0626665e-07, 1.0125469e-08, 1.2107997e-04, 1.8022432e-04,
        1.0341022e-11, 6.6419022e-07, 2.0343361e-14, 9.9969208e-01,
        9.2945891e-07, 4.9578143e-06],
       [2.1306519e-07, 7.2379677e-05, 9.9992418e-01, 2.2975219e-06,
        1.0729308e-14, 1.0675988e-07, 3.3099036e-07, 7.6897259e-11,
        4.8297022e-07, 8.9098617e-11],
       [2.5360309e-06, 9.9744427e-01, 1.7416067e-04, 2.1338237e-05,
        1.4951408e-04, 2.6130203e-05, 7.7626981e-05, 8.2574494e-04,
        1.2774051e-03, 1.3526176e-06],
       [9.9993658e-01, 2.0357776e-08, 5.0056260e-05, 3.1859482e-08,
        1.1652479e-08, 2.0268212e-07, 3.3575750e-06, 2.3160869e-06,
        1.1111388e-09, 7.4696341e-06],
       [5.2047164e-07, 1.7929253e-08, 6.0053567e-06, 1.3590568e-08,
        9.9487114e-01, 4.4925766e-08, 4.0314658e-06, 5.1058066e-04,
        4.1577829e-07, 4.6071797e-03]], dtype=float32)>